language: java
sudo: false
jdk:
- openjdk8
services:
  - mysql
env:
  global:
    - TEST_RUNNER_URI=/tests/tests/run.cfm?reporter=text
    - DB_USER=travis
    - DB_PASS=
  matrix:
    - CFENGINE=lucee@4.5
    - CFENGINE=lucee@5
    - CFENGINE=adobe@10
    - CFENGINE=adobe@11
    - CFENGINE=adobe@2016
before_install:
- git clone --depth 1 https://github.com/foundeo/cfmatrix.git cfmatrix
- mysql -e 'CREATE DATABASE IF NOT EXISTS buglog;'
install:
- bash ./cfmatrix/install.sh
- mysql buglog < tests/BugLogHQ/install/mysql.sql
before_script:
- cfmatrix/bin/box cfconfig cfmapping list
script:
- bash ./cfmatrix/run.sh
- cfmatrix/bin/box server log
